#!/usr/bin/env bash

ethernet (){
  nmcli d | grep ethernet | grep \ connected | wc -l
}

wifi (){
  nmcli d | grep wifi | grep \ connected | wc -l
}

if [ $(ethernet) -eq 1 ]; then
  echo ""
elif [ $(wifi) -eq 1 ]; then
  echo ""
else
  echo ""
fi
