#!/usr/bin/env bash

ethernet (){
  ip -j route get 192.0.2.0 | jq -r '.[0].dev | startswith("e")'
}

wifi (){
  ip -j route get 192.0.2.0 | jq -r '.[0].dev | startswith("wl")'
}

if [ $(ethernet) == 'true' ]; then
  echo ""
elif [ $(wifi) == 'true' ]; then
  echo ""
else
  echo ""
fi
