#!/usr/bin/env bash

declare -A map
map=(
  ["English (US)"]=""
  ["Colemak_DH"]="󰻺"
  ["Graphite"]=""
)

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  layout=$(echo $line | grep activelayout | awk -F',' '{print $NF}')
  if [[ -z ${layout} ]]; then 
    continue 
  fi 
  if [[ -n "${map[$layout]}" ]]; then
    echo "${map[$layout]}"
  else
    echo "${layout:0:2}" | awk '{print toupper($1)}'
  fi
done
