#!/usr/bin/env bash

active (){
	hyprctl activeworkspace -j | jq -c '.id'
}

active
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	active
done
